# Generated by Django 2.0.2 on 2020-04-17 19:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.TextField(blank=True, null=True)),
                ('datos', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
        ),
    ]
