# Generated by Django 2.2.14 on 2021-03-16 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accesos',
            fields=[
                ('id_acceso', models.BigAutoField(db_column='ID_ACCESO', primary_key=True, serialize=False)),
                ('a_nombre_acceso', models.CharField(blank=True, db_column='A_NOMBRE_ACCESO', max_length=20, null=True)),
                ('a_valor_acceso_char', models.CharField(blank=True, db_column='A_VALOR_ACCESO_CHAR', max_length=100, null=True)),
                ('d_fecha_creacion', models.DateTimeField(blank=True, db_column='D_FECHA_CREACION', null=True)),
            ],
            options={
                'db_table': 'SGDP_ACCESOS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AccionesHistInstDeTareas',
            fields=[
                ('id_accion_historico_inst_de_tarea', models.BigIntegerField(db_column='ID_ACCION_HISTORICO_INST_DE_TAREA', primary_key=True, serialize=False)),
                ('a_nombre_accion', models.CharField(db_column='A_NOMBRE_ACCION', max_length=30)),
                ('a_desc_accion', models.CharField(blank=True, db_column='A_DESC_ACCION', max_length=255, null=True)),
            ],
            options={
                'db_table': 'SGDP_ACCIONES_HIST_INST_DE_TAREAS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArchivosInstDeTarea',
            fields=[
                ('id_archivos_inst_de_tarea', models.BigIntegerField(db_column='ID_ARCHIVOS_INST_DE_TAREA', primary_key=True, serialize=False)),
                ('a_nombre_archivo', models.CharField(db_column='A_NOMBRE_ARCHIVO', max_length=1000)),
                ('a_mime_type', models.CharField(blank=True, db_column='A_MIME_TYPE', max_length=100, null=True)),
                ('id_archivo_cms', models.CharField(db_column='ID_ARCHIVO_CMS', max_length=100)),
                ('a_version', models.CharField(db_column='A_VERSION', max_length=100)),
                ('id_usuario', models.CharField(blank=True, db_column='ID_USUARIO', max_length=30, null=True)),
                ('d_fecha_subido', models.DateTimeField(blank=True, db_column='D_FECHA_SUBIDO', null=True)),
                ('b_esta_visado', models.BooleanField(blank=True, db_column='B_ESTA_VISADO', null=True)),
                ('b_esta_firmado_con_fea_web_start', models.BooleanField(blank=True, db_column='B_ESTA_FIRMADO_CON_FEA_WEB_START', null=True)),
                ('b_esta_firmado_con_fea_centralizada', models.BooleanField(blank=True, db_column='B_ESTA_FIRMADO_CON_FEA_CENTRALIZADA', null=True)),
                ('d_fecha_documento', models.DateTimeField(blank=True, db_column='D_FECHA_DOCUMENTO', null=True)),
                ('d_fecha_recepcion', models.DateTimeField(blank=True, db_column='D_FECHA_RECEPCION', null=True)),
            ],
            options={
                'db_table': 'SGDP_ARCHIVOS_INST_DE_TAREA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArchivosInstDeTareaMetadata',
            fields=[
                ('id_archivos_inst_de_tarea_metadata', models.BigAutoField(db_column='ID_ARCHIVOS_INST_DE_TAREA_METADATA', primary_key=True, serialize=False)),
                ('a_titulo', models.CharField(blank=True, db_column='A_TITULO', max_length=200, null=True)),
                ('a_autor', models.CharField(blank=True, db_column='A_AUTOR', max_length=200, null=True)),
                ('a_destinatarios', models.CharField(blank=True, db_column='A_DESTINATARIOS', max_length=1000, null=True)),
                ('b_digitalizado', models.BooleanField(blank=True, db_column='B_DIGITALIZADO', null=True)),
                ('d_fecha_documento', models.DateTimeField(blank=True, db_column='D_FECHA_DOCUMENTO', null=True)),
                ('a_nombre_interesado', models.CharField(blank=True, db_column='A_NOMBRE_INTERESADO', max_length=200, null=True)),
                ('a_apellido_paterno', models.CharField(blank=True, db_column='A_APELLIDO_PATERNO', max_length=200, null=True)),
                ('a_apellido_materno', models.CharField(blank=True, db_column='A_APELLIDO_MATERNO', max_length=200, null=True)),
                ('a_rut', models.CharField(blank=True, db_column='A_RUT', max_length=20, null=True)),
                ('a_etiquetas', models.CharField(blank=True, db_column='A_ETIQUETAS', max_length=1000, null=True)),
                ('a_region', models.CharField(blank=True, db_column='A_REGION', max_length=200, null=True)),
                ('a_comuna', models.CharField(blank=True, db_column='A_COMUNA', max_length=200, null=True)),
                ('a_metadata_custom', models.TextField(blank=True, db_column='A_METADATA_CUSTOM', null=True)),
                ('n_flag_envio', models.BigIntegerField(blank=True, db_column='N_FLAG_ENVIO', null=True)),
            ],
            options={
                'db_table': 'SGDP_ARCHIVOS_INST_DE_TAREA_METADATA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AsignacionesNumerosDoc',
            fields=[
                ('id_asignacion_numero_doc', models.BigIntegerField(db_column='ID_ASIGNACION_NUMERO_DOC', primary_key=True, serialize=False)),
                ('n_numero_documento', models.BigIntegerField(db_column='N_NUMERO_DOCUMENTO')),
                ('a_estado', models.CharField(blank=True, db_column='A_ESTADO', max_length=255, null=True)),
                ('d_anio', models.CharField(db_column='D_ANIO', max_length=255)),
                ('d_fecha_creacion', models.DateTimeField(db_column='D_FECHA_CREACION')),
                ('d_fecha_modificacion', models.DateTimeField(blank=True, db_column='D_FECHA_MODIFICACION', null=True)),
            ],
            options={
                'db_table': 'SGDP_ASIGNACIONES_NUMEROS_DOC',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Autores',
            fields=[
                ('id_autor', models.BigAutoField(db_column='ID_AUTOR', primary_key=True, serialize=False)),
                ('a_nombre_autor', models.CharField(db_column='A_NOMBRE_AUTOR', max_length=100)),
            ],
            options={
                'db_table': 'SGDP_AUTORES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cargas',
            fields=[
                ('id_carga', models.BigAutoField(db_column='ID_CARGA', primary_key=True, serialize=False)),
                ('n_cantidad_documentos', models.BigIntegerField(db_column='N_CANTIDAD_DOCUMENTOS')),
                ('a_nombre_serie', models.CharField(blank=True, db_column='A_NOMBRE_SERIE', max_length=200, null=True)),
                ('a_nombre_acuerdo', models.CharField(blank=True, db_column='A_NOMBRE_ACUERDO', max_length=200, null=True)),
                ('a_tipo_acuerdo', models.CharField(blank=True, db_column='A_TIPO_ACUERDO', max_length=200, null=True)),
                ('a_id_transferencia', models.CharField(blank=True, db_column='A_ID_TRANSFERENCIA', max_length=500, null=True)),
                ('d_fecha_creacion', models.DateTimeField(blank=True, db_column='D_FECHA_CREACION', null=True)),
            ],
            options={
                'db_table': 'SGDP_CARGAS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cargo', models.BigIntegerField(db_column='ID_CARGO', unique=True)),
                ('a_nombre_cargo', models.CharField(db_column='A_NOMBRE_CARGO', max_length=255)),
            ],
            options={
                'db_table': 'SGDP_CARGO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CargoResponsabilidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'SGDP_CARGO_RESPONSABILIDAD',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CargoUsuarioRol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'SGDP_CARGO_USUARIO_ROL',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoriaDeTipoDeDocumento',
            fields=[
                ('id_categoria_de_tipo_de_documento', models.BigAutoField(db_column='ID_CATEGORIA_DE_TIPO_DE_DOCUMENTO', primary_key=True, serialize=False)),
                ('a_nombre_de_categoria_de_tipo_de_documento', models.TextField(db_column='A_NOMBRE_DE_CATEGORIA_DE_TIPO_DE_DOCUMENTO')),
            ],
            options={
                'db_table': 'SGDP_CATEGORIA_DE_TIPO_DE_DOCUMENTO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetallesCarga',
            fields=[
                ('id_detalle_carga', models.BigAutoField(db_column='ID_DETALLE_CARGA', primary_key=True, serialize=False)),
                ('a_nombre_documento', models.CharField(blank=True, db_column='A_NOMBRE_DOCUMENTO', max_length=200, null=True)),
                ('a_id_archivo_cms', models.CharField(blank=True, db_column='A_ID_ARCHIVO_CMS', max_length=200, null=True)),
                ('d_fecha_creacion', models.DateTimeField(blank=True, db_column='D_FECHA_CREACION', null=True)),
            ],
            options={
                'db_table': 'SGDP_DETALLES_CARGA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadosDeProcesos',
            fields=[
                ('id_estado_de_proceso', models.BigAutoField(db_column='ID_ESTADO_DE_PROCESO', primary_key=True, serialize=False)),
                ('n_codigo_estado_de_proceso', models.IntegerField(db_column='N_CODIGO_ESTADO_DE_PROCESO')),
                ('a_nombre_estado_de_proceso', models.CharField(blank=True, db_column='A_NOMBRE_ESTADO_DE_PROCESO', max_length=30, null=True)),
            ],
            options={
                'db_table': 'SGDP_ESTADOS_DE_PROCESOS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadosDeTareas',
            fields=[
                ('id_estado_de_tarea', models.BigAutoField(db_column='ID_ESTADO_DE_TAREA', primary_key=True, serialize=False)),
                ('n_codigo_estado_de_tarea', models.IntegerField(db_column='N_CODIGO_ESTADO_DE_TAREA')),
                ('a_nombre_estado_de_tarea', models.CharField(db_column='A_NOMBRE_ESTADO_DE_TAREA', max_length=20)),
            ],
            options={
                'db_table': 'SGDP_ESTADOS_DE_TAREAS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoSolicitudCreacionExp',
            fields=[
                ('id_estado_solicitud_creacion_exp', models.BigAutoField(db_column='ID_ESTADO_SOLICITUD_CREACION_EXP', primary_key=True, serialize=False)),
                ('a_nombre_estado_solicitud_creacion_exp', models.CharField(db_column='A_NOMBRE_ESTADO_SOLICITUD_CREACION_EXP', max_length=20)),
            ],
            options={
                'db_table': 'SGDP_ESTADO_SOLICITUD_CREACION_EXP',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Etapas',
            fields=[
                ('id', models.BigAutoField(db_column='ID_ETAPA', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='A_NOMBRE_ETAPA', max_length=30)),
            ],
            options={
                'db_table': 'SGDP_ETAPAS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FechasFeriados',
            fields=[
                ('a_fecha_feriado', models.CharField(db_column='A_FECHA_FERIADO', max_length=10, primary_key=True, serialize=False)),
                ('d_fecha_feriado', models.DateTimeField(blank=True, db_column='D_FECHA_FERIADO', null=True)),
            ],
            options={
                'db_table': 'SGDP_FECHAS_FERIADOS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricoAccionesInstDeTareas',
            fields=[
                ('id_historico_acciones_inst_de_tareas', models.BigIntegerField(db_column='ID_HISTORICO_ACCIONES_INST_DE_TAREAS', primary_key=True, serialize=False)),
                ('a_nombre_accion', models.CharField(db_column='A_NOMBRE_ACCION', max_length=30)),
            ],
            options={
                'db_table': 'SGDP_HISTORICO_ACCIONES_INST_DE_TAREAS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricoArchivosInstDeTareas',
            fields=[
                ('a_nombre_archivo', models.CharField(db_column='A_NOMBRE_ARCHIVO', max_length=1000)),
                ('a_mime_type', models.CharField(blank=True, db_column='A_MIME_TYPE', max_length=100, null=True)),
                ('id_archivo_cms', models.CharField(db_column='ID_ARCHIVO_CMS', max_length=100)),
                ('a_version', models.CharField(db_column='A_VERSION', max_length=100)),
                ('id_historico_archivos_inst_de_tareas', models.BigIntegerField(db_column='ID_HISTORICO_ARCHIVOS_INST_DE_TAREAS', primary_key=True, serialize=False)),
                ('id_usuario', models.CharField(blank=True, db_column='ID_USUARIO', max_length=30, null=True)),
                ('d_fecha_documento', models.DateTimeField(blank=True, db_column='D_FECHA_DOCUMENTO', null=True)),
                ('d_fecha_recepcion', models.DateTimeField(blank=True, db_column='D_FECHA_RECEPCION', null=True)),
                ('d_fecha_subido', models.DateTimeField(blank=True, db_column='D_FECHA_SUBIDO', null=True)),
            ],
            options={
                'db_table': 'SGDP_HISTORICO_ARCHIVOS_INST_DE_TAREAS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricoDeInstDeTareas',
            fields=[
                ('id_historico_de_inst_de_tarea', models.BigIntegerField(db_column='ID_HISTORICO_DE_INST_DE_TAREA', primary_key=True, serialize=False)),
                ('d_fecha_movimiento', models.DateTimeField(db_column='D_FECHA_MOVIMIENTO')),
                ('id_usuario_origen', models.CharField(db_column='ID_USUARIO_ORIGEN', max_length=30)),
                ('a_comentario', models.TextField(blank=True, db_column='A_COMENTARIO', null=True)),
                ('a_mensaje_excepcion', models.TextField(blank=True, db_column='A_MENSAJE_EXCEPCION', null=True)),
            ],
            options={
                'db_table': 'SGDP_HISTORICO_DE_INST_DE_TAREAS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricoFechaVencInsProc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_hist_fecha_venc_ins_proc', models.BigIntegerField(db_column='ID_HIST_FECHA_VENC_INS_PROC', unique=True)),
                ('d_fecha_vencimiento', models.DateTimeField(db_column='D_FECHA_VENCIMIENTO')),
                ('id_usuario', models.CharField(db_column='ID_USUARIO', max_length=30)),
            ],
            options={
                'db_table': 'SGDP_HISTORICO_FECHA_VENC_INS_PROC',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricoFirmas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_historico_firma', models.BigIntegerField(db_column='ID_HISTORICO_FIRMA', unique=True)),
                ('id_archivo_cms', models.CharField(db_column='ID_ARCHIVO_CMS', max_length=100)),
                ('id_usuario', models.CharField(db_column='ID_USUARIO', max_length=30)),
                ('d_fecha_firma', models.DateTimeField(db_column='D_FECHA_FIRMA')),
                ('a_tipo_firma', models.CharField(db_column='A_TIPO_FIRMA', max_length=100)),
            ],
            options={
                'db_table': 'SGDP_HISTORICO_FIRMAS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricoSeguimientoIntanciaProcesos',
            fields=[
                ('id_historico_instancia_proceso', models.BigAutoField(db_column='ID_HISTORICO_INSTANCIA_PROCESO', primary_key=True, serialize=False)),
                ('id_instancia_proceso', models.BigIntegerField(blank=True, db_column='ID_INSTANCIA_PROCESO', null=True)),
                ('id_usuario', models.CharField(blank=True, db_column='ID_USUARIO', max_length=255, null=True)),
                ('id_usuario_accion', models.CharField(blank=True, db_column='ID_USUARIO_ACCION', max_length=255, null=True)),
                ('a_accion', models.CharField(blank=True, db_column='A_ACCION', max_length=255, null=True)),
                ('d_fecha_accion', models.DateTimeField(blank=True, db_column='D_FECHA_ACCION', null=True)),
                ('a_tipo_de_notificacion', models.CharField(blank=True, db_column='A_TIPO_DE_NOTIFICACION', max_length=255, null=True)),
            ],
            options={
                'db_table': 'SGDP_HISTORICO_SEGUIMIENTO_INTANCIA_PROCESOS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricoSolicitudCreacionExp',
            fields=[
                ('id_historico_solicitud_creacion_exp', models.BigAutoField(db_column='ID_HISTORICO_SOLICITUD_CREACION_EXP', primary_key=True, serialize=False)),
                ('id_usuario_solicitante', models.CharField(db_column='ID_USUARIO_SOLICITANTE', max_length=30)),
                ('id_usuario_creador_expediente', models.CharField(blank=True, db_column='ID_USUARIO_CREADOR_EXPEDIENTE', max_length=30, null=True)),
                ('id_usuario_destinatario', models.CharField(blank=True, db_column='ID_USUARIO_DESTINATARIO', max_length=30, null=True)),
                ('d_fecha_solicitud', models.DateTimeField(db_column='D_FECHA_SOLICITUD')),
                ('d_fecha_atencion', models.DateTimeField(blank=True, db_column='D_FECHA_ATENCION', null=True)),
                ('a_comentario', models.TextField(blank=True, db_column='A_COMENTARIO', null=True)),
                ('a_asunto_materia', models.CharField(db_column='A_ASUNTO_MATERIA', max_length=1000)),
                ('id_usuario', models.CharField(db_column='ID_USUARIO', max_length=30)),
                ('d_fecha', models.DateTimeField(db_column='D_FECHA')),
                ('a_tipo_accion', models.CharField(db_column='A_TIPO_ACCION', max_length=100)),
            ],
            options={
                'db_table': 'SGDP_HISTORICO_SOLICITUD_CREACION_EXP',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricoValorParametroDeTarea',
            fields=[
                ('id_historico_valor_parametro_de_tarea', models.BigAutoField(db_column='ID_HISTORICO_VALOR_PARAMETRO_DE_TAREA', primary_key=True, serialize=False)),
                ('a_valor', models.CharField(blank=True, db_column='A_VALOR', max_length=5000, null=True)),
                ('a_comentario', models.CharField(blank=True, db_column='A_COMENTARIO', max_length=10000, null=True)),
            ],
            options={
                'db_table': 'SGDP_HISTORICO_VALOR_PARAMETRO_DE_TAREA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricoVinculacionExp',
            fields=[
                ('id_historico_vinculacion_exp', models.BigIntegerField(db_column='ID_HISTORICO_VINCULACION_EXP', primary_key=True, serialize=False)),
                ('id_usuario', models.CharField(db_column='ID_USUARIO', max_length=30)),
                ('d_fecha', models.DateTimeField(db_column='D_FECHA')),
                ('a_tipo_accion', models.CharField(db_column='A_TIPO_ACCION', max_length=100)),
                ('a_comentario', models.TextField(db_column='A_COMENTARIO')),
                ('b_vigente', models.BooleanField(blank=True, db_column='B_VIGENTE', null=True)),
            ],
            options={
                'db_table': 'SGDP_HISTORICO_VINCULACION_EXP',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InstanciaProcesoMetadata',
            fields=[
                ('id_instancia_proceso_metadata', models.BigAutoField(db_column='ID_INSTANCIA_PROCESO_METADATA', primary_key=True, serialize=False)),
                ('a_titulo', models.CharField(blank=True, db_column='A_TITULO', max_length=200, null=True)),
                ('a_nombre_interesado', models.CharField(blank=True, db_column='A_NOMBRE_INTERESADO', max_length=200, null=True)),
                ('a_apellido_paterno', models.CharField(blank=True, db_column='A_APELLIDO_PATERNO', max_length=200, null=True)),
                ('a_apellido_materno', models.CharField(blank=True, db_column='A_APELLIDO_MATERNO', max_length=200, null=True)),
                ('a_rut', models.CharField(blank=True, db_column='A_RUT', max_length=20, null=True)),
                ('a_etiquetas', models.CharField(blank=True, db_column='A_ETIQUETAS', max_length=1000, null=True)),
                ('a_region', models.CharField(blank=True, db_column='A_REGION', max_length=200, null=True)),
                ('a_comuna', models.CharField(blank=True, db_column='A_COMUNA', max_length=200, null=True)),
                ('a_metadata_custom', models.TextField(blank=True, db_column='A_METADATA_CUSTOM', null=True)),
                ('d_fecha_creacion', models.DateTimeField(blank=True, db_column='D_FECHA_CREACION', null=True)),
            ],
            options={
                'db_table': 'SGDP_INSTANCIA_PROCESO_METADATA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InstanciasDeProcesos',
            fields=[
                ('id_instancia_de_proceso', models.BigAutoField(db_column='ID_INSTANCIA_DE_PROCESO', primary_key=True, serialize=False)),
                ('d_fecha_inicio', models.DateTimeField(db_column='D_FECHA_INICIO')),
                ('d_fecha_fin', models.DateTimeField(blank=True, db_column='D_FECHA_FIN', null=True)),
                ('a_nombre_expediente', models.CharField(blank=True, db_column='A_NOMBRE_EXPEDIENTE', max_length=100, null=True)),
                ('d_fecha_vencimiento_usuario', models.DateTimeField(blank=True, db_column='D_FECHA_VENCIMIENTO_USUARIO', null=True)),
                ('id_expediente', models.CharField(blank=True, db_column='ID_EXPEDIENTE', max_length=100, null=True)),
                ('id_usuario_inicia', models.CharField(db_column='ID_USUARIO_INICIA', max_length=30)),
                ('id_usuario_termina', models.CharField(blank=True, db_column='ID_USUARIO_TERMINA', max_length=30, null=True)),
                ('b_tiene_documentos_en_cms', models.BooleanField(blank=True, db_column='B_TIENE_DOCUMENTOS_EN_CMS', null=True)),
                ('d_fecha_vencimiento', models.DateTimeField(blank=True, db_column='D_FECHA_VENCIMIENTO', null=True)),
                ('a_emisor', models.CharField(blank=True, db_column='A_EMISOR', max_length=1000, null=True)),
                ('a_asunto', models.CharField(blank=True, db_column='A_ASUNTO', max_length=1000, null=True)),
                ('d_fecha_expiracion', models.DateTimeField(blank=True, db_column='D_FECHA_EXPIRACION', null=True)),
            ],
            options={
                'db_table': 'SGDP_INSTANCIAS_DE_PROCESOS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InstanciasDeTareas',
            fields=[
                ('id_instancia_de_tarea', models.BigIntegerField(db_column='ID_INSTANCIA_DE_TAREA', primary_key=True, serialize=False)),
                ('d_fecha_asignacion', models.DateTimeField(db_column='D_FECHA_ASIGNACION')),
                ('d_fecha_inicio', models.DateTimeField(blank=True, db_column='D_FECHA_INICIO', null=True)),
                ('d_fecha_finalizacion', models.DateTimeField(blank=True, db_column='D_FECHA_FINALIZACION', null=True)),
                ('d_fecha_anulacion', models.DateTimeField(blank=True, db_column='D_FECHA_ANULACION', null=True)),
                ('a_razon_anulacion', models.CharField(blank=True, db_column='A_RAZON_ANULACION', max_length=1000, null=True)),
                ('d_fecha_vencimiento', models.DateTimeField(blank=True, db_column='D_FECHA_VENCIMIENTO', null=True)),
                ('d_fecha_vencimiento_usuario', models.DateTimeField(blank=True, db_column='D_FECHA_VENCIMIENTO_USUARIO', null=True)),
                ('id_usuario_que_asigna', models.CharField(blank=True, db_column='ID_USUARIO_QUE_ASIGNA', max_length=30, null=True)),
            ],
            options={
                'db_table': 'SGDP_INSTANCIAS_DE_TAREAS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InstanciasDeTareasLibres',
            fields=[
                ('id_instancia_de_tarea_libre', models.BigAutoField(db_column='ID_INSTANCIA_DE_TAREA_LIBRE', primary_key=True, serialize=False)),
                ('id_usuario_que_hace_consulta', models.CharField(db_column='ID_USUARIO_QUE_HACE_CONSULTA', max_length=30)),
                ('id_usuario_asigando', models.CharField(db_column='ID_USUARIO_ASIGANDO', max_length=30)),
                ('id_instancia_de_tarea', models.BigIntegerField(db_column='ID_INSTANCIA_DE_TAREA')),
                ('d_fecha_asignacion', models.DateTimeField(db_column='D_FECHA_ASIGNACION')),
                ('d_fecha_finalizacion', models.DateTimeField(blank=True, db_column='D_FECHA_FINALIZACION', null=True)),
                ('d_fecha_vencimiento', models.DateTimeField(blank=True, db_column='D_FECHA_VENCIMIENTO', null=True)),
            ],
            options={
                'db_table': 'SGDP_INSTANCIAS_DE_TAREAS_LIBRES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ListaDeDistribucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_email', models.CharField(db_column='A_EMAIL', max_length=5000)),
                ('a_organizacion', models.CharField(blank=True, db_column='A_ORGANIZACION', max_length=10000, null=True)),
                ('a_cargo', models.CharField(blank=True, db_column='A_CARGO', max_length=10000, null=True)),
            ],
            options={
                'db_table': 'SGDP_LISTA_DE_DISTRIBUCION',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LogCarga',
            fields=[
                ('id_log_carga', models.BigAutoField(db_column='ID_LOG_CARGA', primary_key=True, serialize=False)),
                ('a_descripcion', models.CharField(blank=True, db_column='A_DESCRIPCION', max_length=1000, null=True)),
                ('d_fecha_creacion', models.DateTimeField(blank=True, db_column='D_FECHA_CREACION', null=True)),
            ],
            options={
                'db_table': 'SGDP_LOG_CARGA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LogError',
            fields=[
                ('id_log_error', models.BigAutoField(db_column='ID_LOG_ERROR', primary_key=True, serialize=False)),
                ('a_nombre_error', models.CharField(db_column='A_NOMBRE_ERROR', max_length=30)),
                ('a_mensaje_excepcion', models.TextField(db_column='A_MENSAJE_EXCEPCION')),
                ('d_fecha_error', models.DateTimeField(db_column='D_FECHA_ERROR')),
                ('id_usuario', models.CharField(db_column='ID_USUARIO', max_length=30)),
                ('a_datos_adicionales', models.TextField(blank=True, db_column='A_DATOS_ADICIONALES', null=True)),
            ],
            options={
                'db_table': 'SGDP_LOG_ERROR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LogFueraDeOficina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_log_fuera_de_oficina', models.BigIntegerField(db_column='ID_LOG_FUERA_DE_OFICINA', unique=True)),
                ('id_usuario', models.CharField(db_column='ID_USUARIO', max_length=30)),
                ('d_fecha_actualizacion', models.DateTimeField(db_column='D_FECHA_ACTUALIZACION')),
                ('b_fuera_de_oficina', models.BooleanField(db_column='B_FUERA_DE_OFICINA')),
            ],
            options={
                'db_table': 'SGDP_LOG_FUERA_DE_OFICINA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LogTransacciones',
            fields=[
                ('id_log_transaccion', models.BigIntegerField(db_column='ID_LOG_TRANSACCION', primary_key=True, serialize=False)),
                ('a_nombre_tabla', models.CharField(db_column='A_NOMBRE_TABLA', max_length=30)),
                ('a_accion', models.CharField(db_column='A_ACCION', max_length=30)),
                ('id_usuario', models.CharField(db_column='ID_USUARIO', max_length=30)),
                ('d_fecha_transaccion', models.DateTimeField(blank=True, db_column='D_FECHA_TRANSACCION', null=True)),
                ('a_parametros', models.CharField(db_column='A_PARAMETROS', max_length=4000)),
            ],
            options={
                'db_table': 'SGDP_LOG_TRANSACCIONES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Macroproceso',
            fields=[
                ('id', models.BigAutoField(db_column='ID_MACRO_PROCESO', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='A_NOMBRE_MACRO_PROCESO', max_length=100)),
                ('descripcion', models.CharField(blank=True, db_column='A_DESCRIPCION_MACRO_PROCESO', max_length=100, null=True)),
            ],
            options={
                'db_table': 'SGDP_MACRO_PROCESOS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParametroDeTarea',
            fields=[
                ('id_param_tarea', models.BigAutoField(db_column='ID_PARAM_TAREA', primary_key=True, serialize=False)),
                ('a_nombre_param_tarea', models.CharField(db_column='A_NOMBRE_PARAM_TAREA', max_length=255)),
                ('a_titulo', models.CharField(blank=True, db_column='A_TITULO', max_length=255, null=True)),
            ],
            options={
                'db_table': 'SGDP_PARAMETRO_DE_TAREA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parametros',
            fields=[
                ('id_parametro', models.BigAutoField(db_column='ID_PARAMETRO', primary_key=True, serialize=False)),
                ('a_nombre_parametro', models.CharField(blank=True, db_column='A_NOMBRE_PARAMETRO', max_length=200, null=True)),
                ('a_valor_parametro_char', models.CharField(blank=True, db_column='A_VALOR_PARAMETRO_CHAR', max_length=10000, null=True)),
                ('n_valor_parametro_numerico', models.IntegerField(blank=True, db_column='N_VALOR_PARAMETRO_NUMERICO', null=True)),
            ],
            options={
                'db_table': 'SGDP_PARAMETROS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParametrosArchivoNacional',
            fields=[
                ('id_parametro_archivo_nacional', models.BigAutoField(db_column='ID_PARAMETRO_ARCHIVO_NACIONAL', primary_key=True, serialize=False)),
                ('a_nombre_parametro', models.CharField(blank=True, db_column='A_NOMBRE_PARAMETRO', max_length=200, null=True)),
                ('a_valor_parametro_char', models.CharField(blank=True, db_column='A_VALOR_PARAMETRO_CHAR', max_length=100, null=True)),
                ('d_fecha_creacion', models.DateTimeField(blank=True, db_column='D_FECHA_CREACION', null=True)),
                ('d_fecha_actualizacion', models.DateTimeField(blank=True, db_column='D_FECHA_ACTUALIZACION', null=True)),
            ],
            options={
                'db_table': 'SGDP_PARAMETROS_ARCHIVO_NACIONAL',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParametrosPorContexto',
            fields=[
                ('id_parametro_por_contexto', models.BigAutoField(db_column='ID_PARAMETRO_POR_CONTEXTO', primary_key=True, serialize=False)),
                ('a_nombre_parametro', models.CharField(blank=True, db_column='A_NOMBRE_PARAMETRO', max_length=250, null=True)),
                ('a_valor_contexto', models.CharField(blank=True, db_column='A_VALOR_CONTEXTO', max_length=250, null=True)),
                ('a_valor_parametro_char', models.TextField(blank=True, db_column='A_VALOR_PARAMETRO_CHAR', null=True)),
                ('n_valor_parametro_numerico', models.IntegerField(blank=True, db_column='N_VALOR_PARAMETRO_NUMERICO', null=True)),
            ],
            options={
                'db_table': 'SGDP_PARAMETROS_POR_CONTEXTO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id_permiso', models.BigAutoField(db_column='ID_PERMISO', primary_key=True, serialize=False)),
                ('a_nombre_permiso', models.CharField(db_column='A_NOMBRE_PERMISO', max_length=250)),
            ],
            options={
                'db_table': 'SGDP_PERMISOS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Perspectivas',
            fields=[
                ('id_perspectiva', models.BigAutoField(db_column='ID_PERSPECTIVA', primary_key=True, serialize=False)),
                ('a_nombre_perspectiva', models.CharField(db_column='A_NOMBRE_PERSPECTIVA', max_length=100)),
                ('a_descripcion_perspectiva', models.CharField(blank=True, db_column='A_DESCRIPCION_PERSPECTIVA', max_length=100, null=True)),
            ],
            options={
                'db_table': 'SGDP_PERSPECTIVAS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(db_column='ID_PROCESO', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='A_NOMBRE_PROCESO', max_length=500)),
                ('descripcion', models.CharField(blank=True, db_column='A_DESCRIPCION_PROCESO', max_length=500, null=True)),
                ('vigente', models.BooleanField(blank=True, db_column='B_VIGENTE', null=True)),
                ('dias_habiles_max_duracion', models.IntegerField(db_column='N_DIAS_HABILES_MAX_DURACION')),
                ('confidencial', models.BooleanField(blank=True, db_column='B_CONFIDENCIAL', null=True)),
                ('x_bpmn', models.TextField(blank=True, db_column='X_BPMN', null=True)),
                ('codigo_proceso', models.CharField(blank=True, db_column='A_CODIGO_PROCESO', max_length=20, null=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, db_column='D_FECHA_CREACION', null=True)),
            ],
            options={
                'db_table': 'SGDP_PROCESOS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProcesoFormCreaExp',
            fields=[
                ('id_proceso_form_crea_exp', models.BigAutoField(db_column='ID_PROCESO_FORM_CREA_EXP', primary_key=True, serialize=False)),
                ('a_codigo_proceso', models.CharField(blank=True, db_column='A_CODIGO_PROCESO', max_length=20, null=True)),
                ('id_usuario', models.CharField(db_column='ID_USUARIO', max_length=30)),
                ('d_fecha', models.DateTimeField(db_column='D_FECHA')),
            ],
            options={
                'db_table': 'SGDP_PROCESO_FORM_CREA_EXP',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReferenciasDeTareas',
            fields=[
                ('id_referencia_de_tarea', models.BigAutoField(db_column='ID_REFERENCIA_DE_TAREA', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'SGDP_REFERENCIAS_DE_TAREAS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Responsabilidad',
            fields=[
                ('id', models.BigAutoField(db_column='ID_RESPONSABILIDAD', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='A_NOMBRE_RESPONSABILIDAD', max_length=255)),
            ],
            options={
                'db_table': 'SGDP_RESPONSABILIDAD',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(db_column='ID_ROL', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='A_NOMBRE_ROL', max_length=30)),
            ],
            options={
                'db_table': 'SGDP_ROLES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SolicitudCreacionExp',
            fields=[
                ('id_solicitud_creacion_exp', models.BigIntegerField(db_column='ID_SOLICITUD_CREACION_EXP', primary_key=True, serialize=False)),
                ('id_usuario_solicitante', models.CharField(db_column='ID_USUARIO_SOLICITANTE', max_length=30)),
                ('id_usuario_creador_expediente', models.CharField(blank=True, db_column='ID_USUARIO_CREADOR_EXPEDIENTE', max_length=30, null=True)),
                ('id_usuario_destinatario', models.CharField(blank=True, db_column='ID_USUARIO_DESTINATARIO', max_length=30, null=True)),
                ('d_fecha_solicitud', models.DateTimeField(db_column='D_FECHA_SOLICITUD')),
                ('d_fecha_atencion', models.DateTimeField(blank=True, db_column='D_FECHA_ATENCION', null=True)),
                ('a_comentario', models.TextField(blank=True, db_column='A_COMENTARIO', null=True)),
                ('a_asunto_materia', models.CharField(db_column='A_ASUNTO_MATERIA', max_length=1000)),
            ],
            options={
                'db_table': 'SGDP_SOLICITUD_CREACION_EXP',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(db_column='ID_TAREA', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='A_NOMBRE_TAREA', max_length=500)),
                ('descripcion', models.CharField(blank=True, db_column='A_DESCRIPCION_TAREA', max_length=500, null=True)),
                ('dias_habiles_max_duracion', models.IntegerField(db_column='N_DIAS_HABILES_MAX_DURACION')),
                ('orden', models.IntegerField(db_column='N_ORDEN')),
                ('vigente', models.BooleanField(blank=True, db_column='B_VIGENTE', null=True)),
                ('solo_informar', models.BooleanField(blank=True, db_column='B_SOLO_INFORMAR', null=True)),
                ('obligatoria', models.BooleanField(blank=True, db_column='B_OBLIGATORIA', null=True)),
                ('es_ultima_tarea', models.BooleanField(blank=True, db_column='B_ES_ULTIMA_TAREA', null=True)),
                ('tipo_de_bifurcacion', models.CharField(blank=True, db_column='A_TIPO_DE_BIFURCACION', max_length=250, null=True)),
                ('puede_visar_documentos', models.BooleanField(blank=True, db_column='B_PUEDE_VISAR_DOCUMENTOS', null=True)),
                ('puede_aplicar_fea', models.BooleanField(blank=True, db_column='B_PUEDE_APLICAR_FEA', null=True)),
                ('url_control', models.CharField(blank=True, db_column='A_URL_CONTROL', max_length=255, null=True)),
                ('id_diagrama', models.CharField(blank=True, db_column='ID_DIAGRAMA', max_length=1000, null=True)),
                ('asigna_num_doc', models.BooleanField(blank=True, db_column='B_ASIGNA_NUM_DOC', null=True)),
                ('esperar_resp', models.BooleanField(blank=True, db_column='B_ESPERAR_RESP', null=True)),
                ('conforma_expediente', models.BooleanField(blank=True, db_column='B_CONFORMA_EXPEDIENTE', null=True)),
                ('dias_reseteo', models.IntegerField(blank=True, db_column='N_DIAS_RESETEO', null=True)),
                ('tipo_reseteo', models.CharField(blank=True, db_column='A_TIPO_RESETEO', max_length=255, null=True)),
                ('url_ws', models.CharField(blank=True, db_column='A_URL_WS', max_length=250, null=True)),
                ('distribuye', models.BooleanField(blank=True, db_column='B_DISTRIBUYE', null=True)),
                ('numeracion_auto', models.BooleanField(blank=True, db_column='B_NUMERACION_AUTO', null=True)),
            ],
            options={
                'db_table': 'SGDP_TAREAS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TareasIniciaProcesos',
            fields=[
                ('id_tarea_inicia_proceso', models.BigAutoField(db_column='ID_TAREA_INICIA_PROCESO', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'SGDP_TAREAS_INICIA_PROCESOS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TextoParametroDeTarea',
            fields=[
                ('id_texto_parametro_de_tarea', models.BigAutoField(db_column='ID_TEXTO_PARAMETRO_DE_TAREA', primary_key=True, serialize=False)),
                ('a_texto', models.CharField(db_column='A_TEXTO', max_length=1000)),
            ],
            options={
                'db_table': 'SGDP_TEXTO_PARAMETRO_DE_TAREA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoDeDocumento',
            fields=[
                ('id', models.BigAutoField(db_column='ID_TIPO_DE_DOCUMENTO', primary_key=True, serialize=False)),
                ('nombre', models.TextField(db_column='A_NOMBRE_DE_TIPO_DE_DOCUMENTO')),
                ('conforma_expediente', models.BooleanField(blank=True, db_column='B_CONFORMA_EXPEDIENTE', null=True)),
                ('aplica_visacion', models.BooleanField(blank=True, db_column='B_APLICA_VISACION', null=True)),
                ('aplica_fea', models.BooleanField(blank=True, db_column='B_APLICA_FEA', null=True)),
                ('es_documento_conductor', models.BooleanField(blank=True, db_column='B_ES_DOCUMENTO_CONDUCTOR', null=True)),
                ('numeracion_auto', models.BooleanField(blank=True, db_column='B_NUMERACION_AUTO', null=True)),
                ('cod_tipo_doc', models.CharField(blank=True, db_column='A_COD_TIPO_DOC', max_length=255, null=True)),
                ('nom_comp_cat_tipo_doc', models.CharField(blank=True, db_column='A_NOM_COMP_CAT_TIPO_DOC', max_length=255, null=True)),
            ],
            options={
                'db_table': 'SGDP_TIPOS_DE_DOCUMENTOS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoParametroDeTarea',
            fields=[
                ('id_tipo_parametro_de_tarea', models.BigAutoField(db_column='ID_TIPO_PARAMETRO_DE_TAREA', primary_key=True, serialize=False)),
                ('a_nombre_tipo_parametro_de_tarea', models.CharField(db_column='A_NOMBRE_TIPO_PARAMETRO_DE_TAREA', max_length=1000)),
                ('a_texto_html', models.CharField(db_column='A_TEXTO_HTML', max_length=5000)),
                ('b_comenta', models.BooleanField(blank=True, db_column='B_COMENTA', null=True)),
            ],
            options={
                'db_table': 'SGDP_TIPO_PARAMETRO_DE_TAREA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipos',
            fields=[
                ('id_tipo', models.BigAutoField(db_column='ID_TIPO', primary_key=True, serialize=False)),
                ('a_nombre_tipo', models.CharField(blank=True, db_column='A_NOMBRE_TIPO', max_length=20, null=True)),
                ('d_fecha_creacion', models.DateTimeField(blank=True, db_column='D_FECHA_CREACION', null=True)),
            ],
            options={
                'db_table': 'SGDP_TIPOS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TiposDeTareasLibres',
            fields=[
                ('id_tipo_de_tarea_libre', models.BigIntegerField(db_column='ID_TIPO_DE_TAREA_LIBRE', primary_key=True, serialize=False)),
                ('a_nombre_de_tarea_libre', models.CharField(db_column='A_NOMBRE_DE_TAREA_LIBRE', max_length=100)),
            ],
            options={
                'db_table': 'SGDP_TIPOS_DE_TAREAS_LIBRES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Unidades',
            fields=[
                ('id', models.BigAutoField(db_column='ID_UNIDAD', primary_key=True, serialize=False)),
                ('codigo_unidad', models.CharField(db_column='A_CODIGO_UNIDAD', max_length=30)),
                ('nombre', models.CharField(blank=True, db_column='A_NOMBRE_COMPLETO_UNIDAD', max_length=100, null=True)),
            ],
            options={
                'db_table': 'SGDP_UNIDADES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioNotificacionTarea',
            fields=[
                ('id_usuario_notificacion_tarea', models.BigAutoField(db_column='ID_USUARIO_NOTIFICACION_TAREA', primary_key=True, serialize=False)),
                ('id_usuario', models.CharField(blank=True, db_column='ID_USUARIO', max_length=30, null=True)),
                ('d_fecha_creacion', models.DateTimeField(blank=True, db_column='D_FECHA_CREACION', null=True)),
            ],
            options={
                'db_table': 'SGDP_USUARIO_NOTIFICACION_TAREA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioResponsabilidad',
            fields=[
                ('id_usuario', models.CharField(db_column='ID_USUARIO', max_length=255)),
                ('id_usuario_responsabilidad', models.BigAutoField(db_column='ID_USUARIO_RESPONSABILIDAD', primary_key=True, serialize=False)),
                ('n_orden', models.IntegerField(blank=True, db_column='N_ORDEN', null=True)),
                ('b_subrogando', models.BooleanField(blank=True, db_column='B_SUBROGANDO', null=True)),
            ],
            options={
                'db_table': 'SGDP_USUARIO_RESPONSABILIDAD',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuariosRoles',
            fields=[
                ('id', models.BigAutoField(db_column='ID_USUARIO_ROL', primary_key=True, serialize=False)),
                ('id_usuario', models.CharField(db_column='ID_USUARIO', max_length=30)),
                ('activo', models.BooleanField(blank=True, db_column='B_ACTIVO', null=True)),
                ('fuera_de_oficina', models.BooleanField(blank=True, db_column='B_FUERA_DE_OFICINA', null=True)),
                ('nombre_completo', models.CharField(blank=True, db_column='A_NOMBRE_COMPLETO', max_length=200, null=True)),
                ('rut', models.CharField(blank=True, db_column='A_RUT', max_length=20, null=True)),
            ],
            options={
                'db_table': 'SGDP_USUARIOS_ROLES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ValorParametroDeTarea',
            fields=[
                ('id_valor_parametro_de_tarea', models.BigAutoField(db_column='ID_VALOR_PARAMETRO_DE_TAREA', primary_key=True, serialize=False)),
                ('a_valor', models.CharField(blank=True, db_column='A_VALOR', max_length=5000, null=True)),
                ('d_fecha', models.DateTimeField(blank=True, db_column='D_FECHA', null=True)),
                ('a_comentario', models.CharField(blank=True, db_column='A_COMENTARIO', max_length=10000, null=True)),
            ],
            options={
                'db_table': 'SGDP_VALOR_PARAMETRO_DE_TAREA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VinculacionExp',
            fields=[
                ('id_vinculacion_exp', models.BigIntegerField(db_column='ID_VINCULACION_EXP', primary_key=True, serialize=False)),
                ('id_usuario', models.CharField(db_column='ID_USUARIO', max_length=30)),
                ('d_fecha_vinculacion', models.DateTimeField(db_column='D_FECHA_VINCULACION')),
                ('a_comentario', models.TextField(db_column='A_COMENTARIO')),
            ],
            options={
                'db_table': 'SGDP_VINCULACION_EXP',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(db_column='ID_ZONA', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=255)),
            ],
            options={
                'db_table': 'SGDP_ZONA',
                'managed': True,
                'unique_together': {('nombre',)},
            },
        ),
        migrations.DeleteModel(
            name='Canal',
        ),
        migrations.CreateModel(
            name='DocumentosDeSalidaDeTareas',
            fields=[
                ('id_tarea', models.ForeignKey(db_column='ID_TAREA', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='base.Tarea')),
                ('n_orden', models.IntegerField(blank=True, db_column='N_ORDEN', null=True)),
            ],
            options={
                'db_table': 'SGDP_DOCUMENTOS_DE_SALIDA_DE_TAREAS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricoUsuariosAsignadosATareas',
            fields=[
                ('id_historico_de_inst_de_tarea', models.ForeignKey(db_column='ID_HISTORICO_DE_INST_DE_TAREA', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='base.HistoricoDeInstDeTareas')),
                ('id_usuario', models.CharField(db_column='ID_USUARIO', max_length=100)),
            ],
            options={
                'db_table': 'SGDP_HISTORICO_USUARIOS_ASIGNADOS_A_TAREAS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParametroRelacionTarea',
            fields=[
                ('id_tarea', models.ForeignKey(db_column='ID_TAREA', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='base.Tarea')),
            ],
            options={
                'db_table': 'SGDP_PARAMETRO_RELACION_TAREA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResponsabilidadTarea',
            fields=[
                ('id_responsabilidad', models.ForeignKey(db_column='ID_RESPONSABILIDAD', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='base.Responsabilidad')),
            ],
            options={
                'db_table': 'SGDP_RESPONSABILIDAD_TAREA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SeguimientoIntanciaProcesos',
            fields=[
                ('id_instancia_proceso', models.ForeignKey(db_column='ID_INSTANCIA_PROCESO', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='base.InstanciasDeProcesos')),
                ('id_usuario', models.CharField(db_column='ID_USUARIO', max_length=64)),
                ('a_tipo_de_notificacion', models.CharField(blank=True, db_column='A_TIPO_DE_NOTIFICACION', max_length=255, null=True)),
            ],
            options={
                'db_table': 'SGDP_SEGUIMIENTO_INTANCIA_PROCESOS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TareasRoles',
            fields=[
                ('id_tarea', models.ForeignKey(db_column='ID_TAREA', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='base.Tarea')),
                ('n_orden', models.IntegerField(blank=True, db_column='N_ORDEN', null=True)),
            ],
            options={
                'db_table': 'SGDP_TAREAS_ROLES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuariosAsignadosATareas',
            fields=[
                ('id_instancia_de_tarea', models.ForeignKey(db_column='ID_INSTANCIA_DE_TAREA', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='base.InstanciasDeTareas')),
                ('id_usuario', models.CharField(db_column='ID_USUARIO', max_length=30)),
            ],
            options={
                'db_table': 'SGDP_USUARIOS_ASIGNADOS_A_TAREAS',
                'managed': False,
            },
        ),
    ]
