# Generated by Django 2.2.14 on 2021-03-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0010_auto_20200416_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='datos',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sid',
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='name'),
        ),
    ]
